# Generated by Django 3.1.2 on 2021-04-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50)),
                ('studentId', models.CharField(max_length=50)),
                ('section1_marks', models.IntegerField(blank=True, null=True)),
                ('section2_marks', models.IntegerField(blank=True, null=True)),
                ('section3_marks', models.IntegerField(blank=True, null=True)),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('Response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Questions.answerkey')),
                ('test_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.configcreation')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='SectionMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_attempted', models.IntegerField(blank=True, null=True)),
                ('section1_correct', models.IntegerField(blank=True, null=True)),
                ('section1_incorrect', models.IntegerField(blank=True, null=True)),
                ('section2_attempted', models.IntegerField(blank=True, null=True)),
                ('section2_correct', models.IntegerField(blank=True, null=True)),
                ('section2_incorrect', models.IntegerField(blank=True, null=True)),
                ('section3_attempted', models.IntegerField(blank=True, null=True)),
                ('section3_correct', models.IntegerField(blank=True, null=True)),
                ('section3_incorrect', models.IntegerField(blank=True, null=True)),
                ('test_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Questions.configcreation')),
            ],
            options={
                'verbose_name': 'Section Metric',
                'verbose_name_plural': 'Section Metrics',
            },
        ),
    ]
