# Generated by Django 3.1.2 on 2021-04-10 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCreation',
            fields=[
                ('testCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dateCreated', models.CharField(max_length=15)),
                ('timeCreated', models.CharField(max_length=15)),
                ('quizName', models.CharField(max_length=50, null=True)),
                ('quizDescription', models.TextField()),
                ('idFormat', models.CharField(max_length=15)),
                ('scheduledDate', models.CharField(max_length=20)),
                ('scheduledTime', models.CharField(max_length=20)),
                ('allowCalculator', models.CharField(blank=True, max_length=50)),
                ('keepQuestion', models.BooleanField(blank=True, default=False)),
                ('shuffleQuestions', models.BooleanField(default=False)),
                ('shuffleOptions', models.BooleanField(default=False)),
                ('sectionCount', models.IntegerField()),
                ('questionCountSec_1', models.IntegerField()),
                ('questionCountSec_2', models.IntegerField(blank=True, null=True)),
                ('questionCountSec_3', models.IntegerField(blank=True, null=True)),
                ('positivesPerQuestionSec_1', models.IntegerField()),
                ('positivesPerQuestionSec_2', models.IntegerField(blank=True, null=True)),
                ('positivesPerQuestionSec_3', models.IntegerField(blank=True, null=True)),
                ('negativesPerQuestionSec_1', models.IntegerField()),
                ('negativesPerQuestionSec_2', models.IntegerField(blank=True, null=True)),
                ('negativesPerQuestionSec_3', models.IntegerField(blank=True, null=True)),
                ('examDuration', models.IntegerField()),
                ('testCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Configuration',
                'verbose_name_plural': 'Question Configurations',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionNumber', models.IntegerField()),
                ('questionNumber', models.IntegerField()),
                ('question', models.TextField()),
                ('option_1', models.TextField()),
                ('option_2', models.TextField()),
                ('option_3', models.TextField()),
                ('option_4', models.TextField()),
                ('isMultiCorrect', models.BooleanField(default=False, null=True)),
                ('ans_1', models.BooleanField(default=False, null=True)),
                ('ans_2', models.BooleanField(default=False, null=True)),
                ('ans_3', models.BooleanField(default=False, null=True)),
                ('ans_4', models.BooleanField(default=False, null=True)),
                ('test_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.configcreation')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50)),
                ('studentId', models.CharField(max_length=50)),
                ('responseFile', models.FileField(blank=True, null=True, upload_to='')),
                ('VideoFile', models.FileField(blank=True, null=True, upload_to='')),
                ('test_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.configcreation')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
